name: coolbeans_clean  # Change this from 'coolbeans' to 'coolbeans_clean'
description: A Flutter review app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  carousel_slider: ^5.1.2
  flutter:
    sdk: flutter
  path_provider: ^2.1.6

dependency_overrides:
  objective_c: 9.0.0
  hooks: 2.0.2
  ffigen: 11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/profile/